### ISSUE TITLE
Action Names - suggestion

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#16]
Here is a suggestion for button actions:

Sync Categories
Sync Products
Sync WYSIWYG
Flush /media/tmp
Reset IC Table

We reduce the space by removing Images word. The last button name should explain what is doing as action. Reset was a generic name.

**Comment by addison74** [comment]
... and this should be the order of the buttons:

Products
Categories
WYSIWYG
Reset
Flush

**Comment by fballiano** [comment]
I implemented some of your suggestions in https://github.com/fballiano/magento1-image-cleaner/releases/tag/0.7.1 but not everything.

- I kept "media/tmp" instead of "/media/tmp", didn't want people to think it's going outside of the magento's document root
- I kept reset at last, it makes more sense from a module funcionality perspective, that's the last thing you want to do and all of the first ones work on the actual filesystem, only the last one is to restore a previous state

;-)

thanks!!!
