### ISSUE TITLE
Small Improvements

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#3]
**First Change**
Do we need the ID column? Let's say we note the ID's for some images we want to select and delete. But we can do the same thing using file name which is more intuitive for a human without noting too many information on a paper.

**Second Change**
200px for the image size is too big and a scrolling efforts is needed. I recommend 100px. 

**Third Changes**
- I would suggest adding a header for the last column at the right named Action. We keep the same format like in other sections in Magento.
- Instead of adding a link on the image and open it in a new window you could insert on column Action, bellow Delete link a new link named Save. It is more elegant and intuitive. See bellow

![snip](https://user-images.githubusercontent.com/8360474/114270039-d21ae980-9a12-11eb-8119-37646e4110c0.jpg)

**Comment by fballiano** [comment]
1. not really but at the same time it's a way to recognize new/old images based on the ID. also, filename could by duplicated on different content_type_id so we'd have to use a double column key which I think it's not even possible in magento's grids (btw I'd still prefer to have the ID key like every other magento's model).
2. mmm depends on the kind of images, for my customers it may be difficult to recognize a smaller image so I wouldn't go less than 200, at the same time we could make it configurable...
3. header was added
4. if I add the download action I think there should be a massDownload action, which may be challanging (big zip size, timeouts, how to delete the ZIP file after download) so I thought that it would be better not to have a download at all... anyways it's something easy to add

**Comment by fballiano** [comment]
I was trying to add the download action but, when there are multiple actions the column itself renders as combobox:
<img width="572" alt="Schermata 2021-04-10 alle 23 27 36" src="https://user-images.githubusercontent.com/909743/114286220-b2a4b080-9a54-11eb-9165-23c8d8f8a600.png">

which is extremely uncomfortable to use so that's a no.

then I tried add multiple action columns:
<img width="657" alt="Schermata 2021-04-10 alle 23 29 52" src="https://user-images.githubusercontent.com/909743/114286226-c6501700-9a54-11eb-9c9e-808baa639cf7.png">

but that it also ugly (and I'd remove the headers which don't make any sense in that case)

so.. mmmm I'm wondering what makes more sense

**Comment by fballiano** [comment]
I created a rendered and it's now nice and working:

<img width="459" alt="Schermata 2021-04-11 alle 00 49 18" src="https://user-images.githubusercontent.com/909743/114287579-cd305700-9a5f-11eb-8cd9-6da5a7b773ee.png">

I decided to keep the "delete" link as last cause I think it's the most used and easiest to click

**Comment by addison74** [comment]
Excellent job. After using ImaClean for almost 8 years I found a new flavor thanks to you.

When pressing [Cancella] link you should ask "Are you sure?" like in Mass Delete actions. I posted an issue for this.

**Comment by fballiano** [comment]
I've created https://github.com/fballiano/magento1-image-cleaner/issues/10 to remind me about the thumb size ;-)

**Comment by fballiano** [comment]
thumbnail size is now configurable ;-)
